version: '3.1'

services:
  db:
    image: mysql:8.0.17
    container_name: my-mysql
    command: [ '--default-authentication-plugin=mysql_native_password', '--default-storage-engine=innodb' ]
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test_db
    ports:
      - 3306:3306
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/:ro
  integration-server:
    image: integration/integration-server
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./config/docker-config.yaml:/bin/config.yaml
    command: integration-server -config=/bin/config.yaml
    restart: always
    depends_on:
      - "db"
